name = "LipoCons"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LipoCons"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "subverso"
git = "https://github.com/leanprover/subverso"

[[require]]
name = "leango"
git = "https://github.com/gaetanserre/LeanGO"

[[lean_lib]]
name = "LipoCons"
